### ISSUE TITLE
Configurar um SiteTour / Passo-passo

### ISSUE THREAD

**Issue by valessiobrito** [pensandoodireito/participacao-sitebase#1]
Ainda não tive tempo para rodar os ambientes, mas talvez seja importante configurar o "intro.js" de forma bem simples e básica para instruir os usuários.
Vejam aqui alguns exemplos e tutoriais: http://usablica.github.io/intro.js/

Creio que os passos iniciais de participar e usar o ambiente pode fazer parte dessa introdução;  Colocando um botão  "Ajuda"  para fazer o passo-passo novamente, caso o usuário tenha esquecido de como se participa.

**Comment by marcoamarelo** [comment]
Demais Valessio! Vamos usar isso sim, acho que só temos que ter uma cara inicial pra mostrar não é? To ralando aqui pra ter alguma coisa até o final do dia. Vamos falando.

**Comment by valessiobrito** [comment]
@marcoamarelo hoje a noite vou tentar rodar um ambiente de desenvolvimento em minha maquina; Vê se consigo mandar algumas contribuições. 

Será que durante essa semana ou neste final de semana não rola de marcar um "Hackathon", tipo, vamos chamar a galera que esta em BSB para ficar programando no Balaio ou em algum lugar que tenha estrutura mínima (Wifi) e bancadas.

**Comment by marcoamarelo** [comment]
@valessiobrito falei com secretário e ele curtiu muito a ideia. Será que você consegue articular isso? Inclusive mobilizando o povo. O que a secretaria puder colaborar vamos tentar ajudar. Só eu que vou ter um pouco de dificuldade por conta do empenho na contribuição da plataforma até o dia 28.

**Comment by valessiobrito** [comment]
@marcoamarelo vou ver o que posso fazer!  Foca ai.. :D
