### ISSUE TITLE
Transformar a núvem de palavras dinâmica

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#108]

**Comment by marilucchesi** [comment]
http://worditout.com/word-cloud/829733

**Comment by marilucchesi** [comment]
If you ever need to make changes to any of your word clouds, here is your personal Secret Link (keep it safe!):

http://worditout.com/user/406219/settings/c4085a4c194ee34445a63d982e16a5b7

**Comment by thsl** [comment]
Infelizmente aplicar a nuvem em texto não é possível, pois afeta a responsividade.
No entanto, a melhor solução será aplicar a imagem melhorada da nuvem de tags

**Comment by diraol** [comment]
Será que não rola pegarmos a imagem e vetorizarmos ela em um SVG?

---

Diego Rabatone Oliveira
diraol(arroba)diraol(ponto)eng(ponto)br
Identica: (@diraol) http://identi.ca/diraol
Twitter: @diraol

Em 7 de maio de 2015 14:27, Thiago Lopes notifications@github.com
escreveu:

**Comment by thsl** [comment]
Testei o SVG, porém cabe analisar com mais dedicação, para encontrarmos a melhor solução.
Por enquanto vou utilizar a imagem gerada mesmo.
