### ISSUE TITLE
Requalificar o Como Participar e incluir orientações de "Como montar um decreto"

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#109]

**Comment by marilucchesi** [comment]
aguardando despacho @marcoamarelo

**Comment by diraol** [comment]
Isso vai ser deixado de lado mesmo? ....

**Comment by marcoamarelo** [comment]
Não @diraol, já atualizamos o texto.

Marco Antonio Konopacki

## @marcoamarelo

...... __@
...._ \ >_
...(_)/ (_)

Em 14 de maio de 2015 16:52, Diego Rabatone Oliveira <
notifications@github.com> escreveu:
