### ISSUE TITLE
Debate em Números: Incluir as 10 pautas mais comentadas com autor

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#111]

**Comment by marilucchesi** [comment]
![uploads/eaa3e709-633a-4668-81c5-ee9a011d6b34/dados_de_acesso.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feaa3e709-633a-4668-81c5-ee9a011d6b34%2Fdados_de_acesso.png)
