### ISSUE TITLE
Remover "signup_extra_fields" 

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#116]
Remover regra de "signup_extra_fields" e respectiva função do arquivo "functions.php" do participacao-tema.
Fazer isso após resolver a issue #115.

**Comment by marcoamarelo** [comment]
Manter a regra, pois mesmo com uma tela de inscrição custom, pode-se querer não usar o cadastro personalizado. Ainda assim, o recurso de cadastro funcionará.
