### ISSUE TITLE
AC: Montar front-end.php com o layout sugerido

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#120]

**Comment by marilucchesi** [comment]
Lembrar de incluir a seção "ficha técnica"
![uploads/b9f6c807-7622-44f6-96bc-d460ae60742d/Debate.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb9f6c807-7622-44f6-96bc-d460ae60742d%2FDebate.png)
