### ISSUE TITLE
AC: Nova página da single de pauta - layout

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#123]

**Comment by marilucchesi** [comment]
![uploads/236e8cf1-375c-4510-aa8d-182189521aa8/Detalhe_Pauta.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F236e8cf1-375c-4510-aa8d-182189521aa8%2FDetalhe_Pauta.png)

**Comment by diraol** [comment]
@marilucchesi Aquele "Número de comentários" (box à direita) vai mostrar o número de comentários da "pauta" sendo visualizada??

**Comment by marilucchesi** [comment]
@diraol isso!
