### ISSUE TITLE
Ajustar bug de CSS na exibição do ante-projeto

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#125]

**Comment by thsl** [comment]
O bug parece afetar quase todas as páginas. Ainda estou verificando o que diabos aconteceu

**Comment by thsl** [comment]
Este bug foi corrigido, mas afetou quase todos os repositórios de css e less, coisas simples, mas afetou. 
Também aproveitei e corrigi a issue 129.
