### ISSUE TITLE
Notícias:  Criar uma imagem padrão para quando não existir uma no destaque

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#14]

**Comment by marilucchesi** [comment]
![uploads/27fc43ab-369a-4c9b-b2f8-20859caeb455/imagem-noticias-big.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F27fc43ab-369a-4c9b-b2f8-20859caeb455%2Fimagem-noticias-big.gif)

**Comment by diraol** [comment]
Passado para a issue #15
