### ISSUE TITLE
Inclusão do plugin email-newsletter no composer.json

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#142]
Disponibiilizar uma maneira de enviar emails de comunicação para todos os cadastrados na plataforma.

**Comment by diraol** [comment]
@marcoamarelo para avaliar essa questão: http://www.wpbeginner.com/opinion/why-you-should-never-use-wordpress-to-send-newsletter-emails/

**Comment by diraol** [comment]
Bem, avaliei dois plugins que achei interessantes:
https://wordpress.org/plugins/email-newsletter/
https://wordpress.org/plugins/knews/
O **knews** me pareceu melhor que o **email-newsletter**, o único porém é que o **email-newsletter** consegue enviar email para a lista de usuários "registrados" no site, enquanto o **knews** precisa que os usuários seja cadastrados numa lista de "assinatura", e não está automatizada uma importação da lista de usuários cadastrados.
Por outro lado, o "email newsletter" não tem um "editor de email wysiwyg". Ele aceita emails em HTML, mas precisa "fazer na mão".

Acho que seria interessante a Elisa e a @marilucchesi avaliarem os plugins....

**Comment by marilucchesi** [comment]
vou ver com a Elisa, @diraol !
@diraol pra ter uma msitura dos dois tipos teria que ser algo tipo o http://www.mailgun.com/ ?? ou https://www.mailpoet.com/? Será que algum funciona pra gente?

**Comment by diraol** [comment]
@marilucchesi o MailGun acho que não serve, porque ele é um serviço de envio de email, e não um plugin do wordpress. Ai seria meio que a mesma coisa que usar o mailchimp.

Quanto ao mailpoet, ele é um plugin para o wordpress e dá para usar, mas ele tem o mesmo problema do knews, que não consegue enviar email para os "usuários da plataforma", mas apenas para "usuários que subscreveram a um form de newsletter".
