### ISSUE TITLE
Criar imagens de formatação dos destaques para incluir no admin

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#144]
vídeo + manchete
imagem + manchete
Imagem ou video full-width

**Comment by diraol** [comment]
@marilucchesi faz 4 opções.
- Vídeo + manchete
- Imagem + manchete
- Imagem full
- Vídeo full

Isso só para manter a consistência dos seletores de imagem e/ou vídeo.

**Comment by marilucchesi** [comment]
![uploads/56b56667-e40b-4961-8ae1-81a7217b581f/imagem-txt.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F56b56667-e40b-4961-8ae1-81a7217b581f%2Fimagem-txt.png)

![uploads/84d59f1c-4e8d-42da-8ec5-d3a0499ae975/video-full.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F84d59f1c-4e8d-42da-8ec5-d3a0499ae975%2Fvideo-full.png)

![uploads/6a351219-77a7-42f9-8149-f59a99da147e/video-txt.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6a351219-77a7-42f9-8149-f59a99da147e%2Fvideo-txt.png)

![uploads/e12b566d-08ba-4e16-8806-175dd568424d/imagem-full.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe12b566d-08ba-4e16-8806-175dd568424d%2Fimagem-full.png)

![uploads/be5f3ff7-1962-4e92-8522-b4ce61054761/admin_destaques.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe5f3ff7-1962-4e92-8522-b4ce61054761%2Fadmin_destaques.png)

**Comment by marilucchesi** [comment]
@diraol coloquei as imagens aqui, vc consegue pegar?

**Comment by diraol** [comment]
Consegui sim @marilucchesi , valeu! =)
