### ISSUE TITLE
[Intercâmbio] Implementar o Layout do blog

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#146]
relacionada ao #143

**Comment by marilucchesi** [comment]
![uploads/f16bcf76-c082-409d-915e-a508b7d99ebd/Programa_de_intercambio.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff16bcf76-c082-409d-915e-a508b7d99ebd%2FPrograma_de_intercambio.png)

**Comment by diraol** [comment]
Vinculado a #149

**Comment by thsl** [comment]
Criei a página page-intercambio.php, ao invés da font-page.php.
