### ISSUE TITLE
Debates: Incluir a seção "HIPERTEXTO" no lugar de notícias

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#16]

**Comment by diraol** [comment]
Usar técnica de filtros do wordpress para modificar o título da área (Notícias e/ou Hipertexto)

**Comment by diraol** [comment]
Atenção ao botão de "Mais Itens"

**Comment by marcoamarelo** [comment]
Pensar melhor nessa issue tentando melhorar o cenário quando debate terá área de notícias ou não, como isso irá se comportar.

**Comment by diraol** [comment]
Acho que o ideal seria criar um Widget "Hipertexto" e criar uma área na front-page que permita adicionar ou não widgets. Ai, caso a caso, pode-se adicionar.
Este widget deveria também permitir a inserção de uma lista de tags que seriam utilizadas para filtrar as notícias que devem aparecer.
