### ISSUE TITLE
Apresentar outras pautas na capa

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#167]
Uma das pautas, "Foro privilegiado" não está aparecendo na capa, porque ela não foi comentada. Ela só aparecerá se houver algum comentário nela, no entanto, temos que pensar numa forma que ela apareça como "outras pautas", se não só pautas com comentários terão novos comentários, outras ficarão esquecidas. @thsl pense numa forma de incluir essa área ali. Se der tempo de fazermos hoje, já publicamos com esse nosso release de melhoria.

**Comment by thsl** [comment]
Quando não houver comentários, a pauta trará a descrição dela. Se não me engano já havíamos previsto isto...

**Comment by marcoamarelo** [comment]
Eu to criando um link para visualizar todas as pautas no eixo, avisando que ali só estão listadas as recém comentadas, acho que irá resolver com a adaptação que estou fazendo na #166.
