### ISSUE TITLE
grande dificuldade na leitura dos comentários

### ISSUE THREAD

**Issue by ddoneda** [pensandoodireito/participacao-sitebase#2]
Os comentários já realizados aos artigos do Anteprojeto são visualizados em um box que abre, com uma animação, à direita, ocupando menos de 10% da tela, não importa o número de comentários.
Ocorre que, em um trabalho como este, o texto é tremendamente importante, e o tamanho e a maneabilidade dos comentários deixam muito a desejar.
Acredito que determinados artigos, ao fim do debate, terão dezenas ou mesmo centenas de comentários. A grande dificuldade na visualização, no entanto, ameaça enfraquecer o debate pois, com esta dificuldade, cresce a possibilidade de que novos comentários sejam feitos sem que o comentador tenha lido os comentários anteriores sobre o mesmo tema.
Há ao menos dois grandes problemas com isto: os novos comentários podem não estar contextualizados com os comentários anteriores e poderão ser inibidas algumas eventuais polêmicas que poderiam surgir.
Faço estas observações para que seja estudado, com a rapidez possível, um novo modelo de visualização dos comentários já feitos de modo que os novos comentadores tenham, facilmente, a visualização dos comentários anteriores para que o debate se dê efetivamente em um crescendo.

**Comment by marcoamarelo** [comment]
Foi ajustado o tamanho e a forma de apresentação dos comentários. @ddoneda você pode verificar se isso contempla a sua expectativa?

**Comment by ddoneda** [comment]
Legal Marco, vou responder no outro email que você mandou para todos.

**Comment by ddoneda** [comment]
Não, as modificações não contemplam a demanda da Senacon e de bom número de usuários a respeito da legibilidade e maneabilidade dos comentários já feitos.

**Comment by diraol** [comment]
@ddoneda , a versão atual contempla as necessidades da Senacon? Podemos fechar a issue?

**Comment by ddoneda** [comment]
Resolvido Diego, obrigado!

Apr 1, 2015, alle ore 7:57 PM, Diego Rabatone Oliveira <notifications@github.com <mailto:notifications@github.com>> ha scritto:
