### ISSUE TITLE
PUBLICAÇÕES: limitar caracteres na descrição

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#21]
Via @marilucchesi:
máx 200 caracteres (com css/gradiente)
![captura de tela 2015-03-23 as 17 25 32](https://cloud.githubusercontent.com/assets/10927020/6789791/c4f4cf06-d181-11e4-95ae-0f4fcc2fec87.png)

@thsl depois do @diraol ajustar, vc dá uma olhada pra criar o css do gradiente, blz?

**Comment by marilucchesi** [comment]
@thsl colocar o css para o gradiente no global.css para usarmos em qualquer página. Lembrar de fazer a alteração no html do publicações para aplicar o efeito.

**Comment by marilucchesi** [comment]
lembrar de limitar também na descrição da publicacao em destaque (530 caracteres)

**Comment by diraol** [comment]
@marilucchesi 530 é MUITA coisa... coloquei 50, o que deu umas 11 linhas. (o CSS não está implementado)

**Comment by marilucchesi** [comment]
@diraol 530 é para a publicação EM DESTAQUE, a que fica no box maior. Para a do card pode colocar 200 que o css vai cobrir. @thsl o css já foi??

**Comment by diraol** [comment]
​Ok, mudei. Fiz o ajusto para os dois e subi no master já.

**Comment by marilucchesi** [comment]
boa!

**Comment by diraol** [comment]
Lembrando que falta implementar o css....
