### ISSUE TITLE
Gerar as classes de alinhamento das imagens para o participacação / blog (exemplo aligncenter). Veja um exemplo em https://participacao.mj.gov.br/intercambio/2015/07/22/programacao-cultural-passeios-e-afins/

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#222]

**Comment by thsl** [comment]
Para um melhor funcionamento e adaptação da imagem á caixa, utilize a classe css "img-full";

![uploads/2e1ef3d8-5d66-4f17-b7b3-f5cf09224348/img-full.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2e1ef3d8-5d66-4f17-b7b3-f5cf09224348%2Fimg-full.png)
