### ISSUE TITLE
Criar a ação ajax do "componente" de login "dinâmico"

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#23]
Criar um "componente" para realizar login dos usuários sem que eles precisem sair da página atual. Este componente será utilizado quando um usuário não estiver logado e tentar votar e/ou comentar e/ou criar uma nova pauta. Assim, ao "efetuar a ação", caso ele não esteja logado será requisitado a ele que faça o login por meio de um "box" que aparecerá sobre a página atual. Ao completar o login a ação continuará e será executada.

**Comment by marcoamarelo** [comment]
http://natko.com/wordpress-ajax-login-without-a-plugin-the-right-way/
