### ISSUE TITLE
Verificar links permanentes (acesso aos links antigos) 

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#24]
confirmar se os links antigos vão funcionar depois das modificações de url.
Em especial o "/blog/publicacao" -> "/publicacao"

**Comment by diraol** [comment]
Verificar junto da #40

**Comment by diraol** [comment]
e da #42

**Comment by diraol** [comment]
Talvez valha uma regra de "rewrite" geral (htaccess? e o nginx?) para redirecionar /blog/ para /

**Comment by diraol** [comment]
O mesmo vale para links "/pensandoodireito/" para "/"

**Comment by marilucchesi** [comment]
Documentar na Wiki da Sprint.
