### ISSUE TITLE
[Publicações] Número das publicações no 'widget'

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#241]
Adicionar o número da publicação em cada publicação apresentada no 'widget' de publicação, que aparece ao lado direito na página de uma única publicação:
http://pensando.mj.gov.br/publicacoes/habeas-corpus-nos-tribunais-superiores/

**Comment by marcoamarelo** [comment]
Com a ideia de termos uma sidebar widgetzável, acredito que teremos que construir um widget de publicação que incluirá esse recurso.
