### ISSUE TITLE
Painel - acompanhamento da própria participação

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#26]
Via @prenass:
Seria possível incluir no painel uma forma de visualizar rapidamente todos os tópicos em que já comentei, além dos tópicos que eu mesmo criei?
Há já algum outro caminho para essa funcionalidade?

Via @marcoamarelo:
É uma funcionalidade bem interessante @prenass, mas teríamos que desenvolvê-la. Vou colocar como prioridade depois de melhorarmos algumas coisas de interação que estão pendentes.

issue original: https://github.com/pensandoodireito/participacao-tema/issues/26

**Comment by marilucchesi** [comment]
relacionado #126
