### ISSUE TITLE
Tageamento colaborativo para apoio a sistematização

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#27]
Seria legal termos um sistema em que as pessoas poderiam sugerir palavras-chave pra comentários e pautas que seriam sugestões individuais. Com o cruzamento das sugestões, poderíamos encontrar palavras-chave mais relevantes.

**Comment by marcoamarelo** [comment]
Recurso foi contemplado pelo uso do serviço hypothes.is.
