### ISSUE TITLE
Permitir definição da senha no cadastro do usuário

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#28]
Como já sabemos, a senha inicialmente atribuída sem participação do usuário vem em formato totalmente imemorizável. Para fazer sua modificação, apenas quem já tem alguma intimidade com o Wordpress vai encontrar o link no canto direito superior. Mas mesmo que o faça, depois de alterada a senha não há caminho de volta para a página principal.

**Comment by marcoamarelo** [comment]
Modificado o objetivo geral para evitar a criação da área de usuário agora

**Comment by marcoamarelo** [comment]
Tarefa foi realizado na issue #78
