### ISSUE TITLE
Gerar o HTML da capa (notícias). Alterar o front-noticias

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#282]
Lembrar de criar um template para filtro por tempo (ano, mês ano, dia mês ano). #425

**Comment by thsl** [comment]
1 - Este push não deve ser integrado e sim feito um merge e assim aplicado aos temas;
2 - O commit desta issue extende-se para dois repositórios: pensandoodireito-tema e participação-tema;
