### ISSUE TITLE
Verificar erro do gulp ao levantar a box

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#298]
==> default: [02:16:29]
==> default: Local gulp not found in /vagrant
==> default: [02:16:29]
==> default: Try running: npm install gulp
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by theoziran** [comment]
Coloquei as dependências do node em arquivo e sua execução local
