### ISSUE TITLE
novas formas de envio de contribuições

### ISSUE THREAD

**Issue by ddoneda** [pensandoodireito/participacao-sitebase#3]
A plataforma do debate permite a participação somente pelos comentários aos artigos. Muitos cidadãos e entidades preferirão enviar as suas sugestões por meio de um documento. É necessária a criação de um espaço ou indicação de endereço para o envio destes documentos. Além disto, é necessária também a definição de um espaço na plataforma no qual serão visualizadas as contribuições que chegarem deste modo.

**Comment by diraol** [comment]
Resolvido.
@marcoamarelo Pode fechar essa issue. =)
