### ISSUE TITLE
Ajuste no provisionamento para fazer o apache rodar com o usuário vagrant e outras condições do diretório raiz

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#305]

**Comment by theoziran** [comment]
@marcoamarelo verifiquei o apache2 e também o sync folder estão tudo alinhados, todas as pastas estão com vagrant como grupo e usuário, e também o apache está configurado para ser (e está sendo) executado com usuário vagrant.

/etc/apache2/apache2.conf:110
ps aux | egrep '(apache|httpd)'
