### ISSUE TITLE
Implementar a lógica de exibição dos últimos comentários agrupados por artigo na capa

### ISSUE THREAD

**Issue by thsl** [pensandoodireito/participacao-sitebase#309]

**Comment by josafafilho** [comment]
O link para o comentário deve seguir a seguinte estrutura: URL DO POST + '#commentable-section-' +NUMERO DA SEÇÃO.

Por exemplo se o bloco de comentário for o 35, e a url do post for http://localhost/marcocivil/texto-em-debate/texto-3/, o link deverá ser http://localhost/marcocivil/texto-em-debate/texto-3/#commentable-section-35.

O número da seção é uma propriedade META do comentário chamada 'side-comment-section'.

**Comment by josafafilho** [comment]
Para consumir o serviço que fornece os ultimos comentários, devem ser passados os seguintes parametros:

URL do Ajax: http://localhost/marcocivil/wp-admin/admin-ajax.php (em dev)

Parâmetros:

--- post_id: Número do Post

--- action: last_comments_callback

--- last_comments_nonce: Nonce Gerado

Pra gerar o nonce:

`$last_comments_nonce = wp_create_nonce('side_comments_last_comments_nonce');`

A branch que tem essa implementação é: https://github.com/josafafilho/wp-side-comments/tree/issue343

**Comment by marcoamarelo** [comment]
O link gerado na capa está incorreto. Pelo que vi está fixo. Minha sugestão é usar essa implementação:

`urlText : '<?php echo get_permalink(413); ?>',`
`postId  : 413,`

**Comment by marcoamarelo** [comment]
O ideal mesmo seria esse ID ser dinâmico, mas se não deixar deixamos fixo mesmo.

**Comment by theoziran** [comment]
Posso deixar dinâmico já que só temos 1 texto, vou pegar o último texto em debate gerar esses itens.
