### ISSUE TITLE
Ajustar editor de texto visual para não gerar novos parágrafos com o mesmo id de comentário já usado

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#314]
Quando estamos alterando um post já existente, no modo de editor visual, ao criar um novo parágrafo no texto, automaticamente, é associado os mesmos atributos do parágrafo anterior. Dessa forma a unicidade dos parágrafos fica comprometida, o que compromete também a exibição correta dos comentários por parágrafo.

**Comment by marcoamarelo** [comment]
Verificar se a issue #405 não resolve essa questão.
