### ISSUE TITLE
Melhoria do composer.json para atualização da versão do WordPress

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#342]

**Comment by theoziran** [comment]
Foram feitos PRs para os repositórios abaixo:

https://github.com/pensandoodireito/marcocivil-tema
https://github.com/pensandoodireito/dadospessoais-tema
https://github.com/pensandoodireito/pensandoodireito-tema
https://github.com/pensandoodireito/participacao-tema
https://github.com/pensandoodireito/pensandoodireito-network-functions
https://github.com/pensandoodireito/wp-side-comments
https://github.com/pensandoodireito/delibera
https://github.com/pensandoodireito/debatepublico-tema
https://github.com/pensandoodireito/blog-tema

**Comment by marcoamarelo** [comment]
@theoziran parece que não gerou o htaccess na hora do provisionamento.
![index-fail](https://cloud.githubusercontent.com/assets/3003517/10594113/6b9b1f92-76a8-11e5-87ce-1a3053c5f38d.png)

**Comment by theoziran** [comment]
Isso aconteceu no computado de @josafafilho mas foi que tinha dado algum problema no composer, quando estava fazendo download, etc. Outra coisa é que para migrar de ambiente tem que apagar a pasta vendor e também o arquivo composer.lock.
