### ISSUE TITLE
Criar o cadastro modal para plataforma

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#350]

**Comment by theoziran** [comment]
Essa issue conterá as correções e observações apontadas nas issues abaixo pois se trata da mesmas funcionalidades e elas são dependentes.
pensandoodireito/participacao-sitebase#394
pensandoodireito/participacao-sitebase#317

**Comment by marcoamarelo** [comment]
1) Ajustar a imagem "O que é" que está se referenciando a imagem relativa do tema (sugiro ter isso no participacao-tema, já que é genérico a toda a plataforma).
2) Quando gera um erro, tem que ter uma opção de voltar para o formulário.
3) Botão de fechar o modal.
