### ISSUE TITLE
Efetuar logout redireciona pra capa, deveria manter na mesma página

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#356]

**Comment by theoziran** [comment]
Implementar uma chamada ajax para logout e assim não se direciona pra lugar nenhum.

**Comment by josafafilho** [comment]
ao completar o logout fazer a seguinte chamada:

`$('body').trigger('user_logged_out');`

Dessa forma o plugin wp-side-comments pode ser notificado e fazer as modificações necessárias na estrutura dos comentários.
