### ISSUE TITLE
Ajuste do parágrafo onde a janela de comentários estava aberta

### ISSUE THREAD

**Issue by thsl** [pensandoodireito/participacao-sitebase#357]
Quando está aberto, e clica-se em outro balão a classe "active" não é removida do parágrafo que estava aberta anteriormente

**Comment by josafafilho** [comment]
Não foi possível reproduzir. Acredito que as implementações anteriores resolveram o problema.

**Comment by josafafilho** [comment]
Consegui reproduzir o problema.

Enquanto uma janela de comentários estiver aberta, é preciso clicar na área em branco abaixo do botão de comentar da outra seção de comentários.
