### ISSUE TITLE
Criar página "parceiros"

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#36]

**Comment by diraol** [comment]
Não esquecer de colocar isso como tarefa da versão para ser aplicada a todas as instâncias (por causa do wp-admin)

**Comment by marilucchesi** [comment]
verificar se os parceiros continuam os mesmos.

**Comment by marilucchesi** [comment]
Consolidado:
Associação dos Advogados de São Paulo

Associação dos Juízes para a Democracia

Associação Nacional dos Defensores Públicos (Anadep)

Associações de defensoria

Central dos Movimentos Populares

Centro Feminista de Estudos e Assessoria (CFEMEA)

Comitê Gestor da Internet no Brasil (CGI.br)

Conselho Nacional de Justiça (CNJ)

Conselho Nacional do Ministério Público 

Cultura Digital & Democracia

Defensoria Pública

Defensoria Pública da União

Defensoria Pública do Estado de São Paulo

Departamento Jurídico XI de Agosto 

Escritório Modelo da PUC-SP

Estratégia Nacional de Combate à Lavagem de Dinheiro (ENCCLA)

Estratégia Nacional de Justiça e Segurança Pública (Enasp)

Federação Nacional de Estudantes de Direito (Fened)

Fórum Justiça 

Instituo Brasileiro de Direito Processual

Instituto Beta para Internet e Democracia (Ibidem)

Instituto Brasileiro de Ciências Criminais (IBCCrim)

Instituto Brasileiro de Defesa do Consumidor (Idec) 

Instituto Brasileiro de Direito de Família

Instituto Brasileiro de Direito Urbanístico (IBDU)

Instituto Carioca de Criminologia (ICC)

Instituto Pólis 

Instituto Scarance

Instituto Sou da Paz

InternetLab 

Intervozes (coletivo)

Movimento do Ministério Público Democrático (MPD)

Movimento dos Trabalhadores Rurais Sem-Terra (MST)

Movimento dos Trabalhadores Sem-Teto (MTST)

Oboré (empresa)

Oficina de Imagens 

Ordem dos Advogados do Brasil (OAB)

Organização Internacional de Polícia Criminal (Interpol)

Pastoral Carcerária

Projeto Cala-boca já morreu

Proteste - Associação Brasileira de Defesa do Consumidor

Rede Nacional de Advogados e Advogados Populares (Renap)

Sociedade Brasileira de Direito Público (SBDP)

Terra de Direitos

União dos Movimentos de Moradia de São Paulo

Via Campesina

World Wide Web Consortium (W3C)
