### ISSUE TITLE
Verificar a altura da caixa de Respostas dos comentários

### ISSUE THREAD

**Issue by diraol** [pensandoodireito/participacao-sitebase#38]
Fazer um "QA test" com relação à caixa de comentários para averiguar em diversas resoluções, telas e navegadores se o tamanho da caixa de comentários está adequado para qualquer quantidade de comentários.

**Comment by diraol** [comment]
No "Dados Pessoais"

**Comment by marilucchesi** [comment]
@diraol coloca uma class chamada "comment-reply"ou algo do tipo na ul dos "comentários resposta", por favor? Obrigada!

**Comment by marilucchesi** [comment]
max-height: 100%;
padding-left: 8px;
border-left: 6px solid #2a8cca;
