### ISSUE TITLE
Avaliação de implementação de um plugin de editoração avançado

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#405]
Sugestões do Téo 

TinyMCE Advanced:

https://wordpress.org/plugins/tinymce-advanced/

WP Edit:
https://wordpress.org/plugins/wp-edit/

O problema principal dele é ter uma ferramenta pra montar tabelas.

**Comment by josafafilho** [comment]
O plugin TinyMCE advanced é bem completo mas tem um alerta de compatibilidade para o wordpress 4.3 ou posterior

O plugin WP Edit também é completo e compatível e tem várias opções de configuração relativos à criação de posts.

Se quisermos apenas disponibilizar a opção de tabelas existe o plugin MCE Table Buttons http://10up.com/plugins/wordpress-mce-table-buttons/

**Comment by marcoamarelo** [comment]
Legal @josafa, eu prefiro o mais simples, o table buttons. A questão está
em relação a aquela questão que queríamos resolver sobre a geração de ids
automáticos pros "p"s, pro seu plugin de texto. Algum deles resolve isso?

Marco Antonio Konopacki

## @marcoamarelo

...... __@
...._ \ >_
...(_)/ (_)

Em 15 de outubro de 2015 09:43, Josafá Filho notifications@github.com
escreveu:

**Comment by josafafilho** [comment]
Não, nenhum desses resolve aquele comportamento. Pelo menos, não consegui identificar nenhuma opção de configuração deles que faça isso. Vou ter que implementar o ajuste.

**Comment by marcoamarelo** [comment]
Então optamos o botão de tabela certo?

Abraços.

Marco Antonio Konopacki

## @marcoamarelo

...... __@
...._ \ >_
...(_)/ (_)

Em 19 de outubro de 2015 16:47, Josafá Filho notifications@github.com
escreveu:

**Comment by josafafilho** [comment]
Acredito que sim, @marcoamarelo. A não ser que o Téo realmente queira um dos outros, mas não vejo motivo pra isso. Preciso adicionar o plugin no nosso composer?

**Comment by marcoamarelo** [comment]
Sim @josafafilho15!

Obrigado.
Em 20 de out de 2015 3:48 PM, "Josafá Filho" notifications@github.com
escreveu:

**Comment by josafafilho** [comment]
@marcoamarelo já fiz o PR adicionando o plugin ao composer
