### ISSUE TITLE
Automatizar verificação dos padrões de codificação com PHP Fixer

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#408]

**Comment by theoziran** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
php php-cs-fixer.phar fix /path/to/dir

**Comment by marcoamarelo** [comment]
Faremos uma reunião no próximo sprint review pra deliberar sobre o padrão de codificação.

**Comment by marcoamarelo** [comment]
Deliberamos pelo padrão do WordPress
