### ISSUE TITLE
Modificar header para suportar menu WordPress Principal e Secudário

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#41]
Usar funções do WordPress para gerar os menus.

**Comment by diraol** [comment]
Deixando link de referência sobre descrição de itens de menu.
http://wordpress.stackexchange.com/questions/14037/menu-items-description-custom-walker-for-wp-nav-menu

**Comment by diraol** [comment]
NECESSÁRIO criar os menus no painel de admin do wordpress.
