### ISSUE TITLE
Melhoria do Slider de destaque da capa

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#412]

**Comment by thsl** [comment]
Detalhes para melhorias:
- Refazer notícias e publicações (contem erros de sintaxe);
- Opção de pausar/iniciar o slider, e também pausa-lo automaticamente ao iniciar um vídeo do youtube;
- Remover o breadcrumb na home (ele não aparece, mas está lá!)
