### ISSUE TITLE
Colocar indexação no site do pensando

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#419]

**Comment by theoziran** [comment]
O plugin foi adicionado no WPackagist
https://wordpress.org/plugins/wordpress-seo/installation/

Observações
1- @marcoamarelo cadastrar o portal no Google Webmasters para cadastrar o site.
https://www.google.com/intl/pt-BR/webmasters/

2- Tornar o robots.txt acessíveis.

**Comment by marcoamarelo** [comment]
Vai ser integrado na próxima versão com a correção da issue #342

**Comment by marcoamarelo** [comment]
Instalado o plugin em produção. Precisa fazer ajustes.
