### ISSUE TITLE
Aplicar melhoria no visual do "Como participar?"

### ISSUE THREAD

**Issue by thsl** [pensandoodireito/participacao-sitebase#427]

**Comment by thsl** [comment]
Opção para o novo visual:

![uploads/55ae13f9-77a2-4f42-aed2-ef02eab062f9/passo-passo.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F55ae13f9-77a2-4f42-aed2-ef02eab062f9%2Fpasso-passo.png)

**Comment by marcoamarelo** [comment]
Aprovado. Estou mudando essa issue para aplicar.
