### ISSUE TITLE
Reordenar seção de comentários recentes na capa do marco civil

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#431]

**Comment by josafafilho** [comment]
As seções não são reordenadas quando inicialmente na tela existe apenas uma seção.

Passo a passo:

1- Configurar texto com apenas um comentário em um parágrafo
2- Fazer comentário em um parágrafo diferente

A segunda coluna aparece, mas ela não fica alinhada a esquerda. O mesmo acontece para um eventual comentário em um terceiro parágrafo. Este comportamento não se repete quando a página já é carregada com 3 seções.

**Comment by theoziran** [comment]
http://quick.as/r3z4unlbr
