### ISSUE TITLE
Remover classe img-redondo

### ISSUE THREAD

**Issue by Gabriel-Pereira-MJ** [pensandoodireito/participacao-sitebase#433]

**Comment by thsl** [comment]
Nota: Avaliar a real aplicabilidade disto, de acordo com a identidade visual do portal.

**Comment by theoziran** [comment]
@thsl ficou de conversar para avaliar a real necessidade dessa funcionalidade com o @Gabriel-Pereira-MJ. E também sobre outras páginas http://goo.gl/z0cRWl http://goo.gl/OB2WBQ

**Comment by thsl** [comment]
Não será implementada por estar fora do padrão visual.
