### ISSUE TITLE
Planejamento visual da biblioteca de publicações

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#484]
Permitir que o usuário possa ter sua biblioteca local de publicações, informando quais publicações já foram baixadas, lidas e etc.

**Comment by thsl** [comment]
Opção:

![uploads/570506f5-6aaa-4145-b455-3ce0d0423971/010-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F570506f5-6aaa-4145-b455-3ce0d0423971%2F010-PENSANDO-APP-V001.jpg)
