### ISSUE TITLE
Planejamento visual da área de notícias do app

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#497]

**Comment by thsl** [comment]
Listagem de notícias:

![uploads/e1472ab1-5007-488e-9819-4a59a5460c7a/008-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe1472ab1-5007-488e-9819-4a59a5460c7a%2F008-PENSANDO-APP-V001.jpg)

Página de leitura de notícias:

![uploads/a5d2e664-57c9-4ec6-bfc5-6ceef8814b09/009-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa5d2e664-57c9-4ec6-bfc5-6ceef8814b09%2F009-PENSANDO-APP-V001.jpg)
