### ISSUE TITLE
Planejamento visual da área de eventos do app

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#498]

**Comment by thsl** [comment]
Listagem de eventos:

![uploads/eaaf595d-b09b-451e-b4fc-711ca20c5517/006-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feaaf595d-b09b-451e-b4fc-711ca20c5517%2F006-PENSANDO-APP-V001.jpg)

Ao selecionar um evento:

![uploads/fa9cbb17-70a5-4834-ac24-10d30a6e8020/007-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa9cbb17-70a5-4834-ac24-10d30a6e8020%2F007-PENSANDO-APP-V001.jpg)

**Comment by josafafilho** [comment]
prever um recurso de abrir aplicativo de mapas externo

**Comment by thsl** [comment]
![uploads/d2c795e2-a3e3-4eca-acbe-e31b7b632b61/011-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd2c795e2-a3e3-4eca-acbe-e31b7b632b61%2F011-PENSANDO-APP-V001.jpg)
