### ISSUE TITLE
Planejamento visual da ára "Sobre" do app

### ISSUE THREAD

**Issue by josafafilho** [pensandoodireito/participacao-sitebase#499]

**Comment by thsl** [comment]
Proposta:

![uploads/e939c22d-3e50-4873-b42e-5281458fee11/005-PENSANDO-APP-V001.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe939c22d-3e50-4873-b42e-5281458fee11%2F005-PENSANDO-APP-V001.jpg)
