### ISSUE TITLE
Bug de comentário repetido em todos os posts. 

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#50]
Provavelmente precisar dar um wp_reset_postdata no final da listagem da sidebar pra corrigir.

**Comment by diraol** [comment]
@marcoamarelo aonde está ocorrendo isso? "Dados Pessoais" ou "Marco Civil"?

**Comment by marcoamarelo** [comment]
Em todos, é bug do template de notícias na verdade ;-)
Em 08/04/2015 4:36 PM, "Diego Rabatone Oliveira" notifications@github.com
escreveu:
