### ISSUE TITLE
Exclusão do menu repetido do header participacao

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#54]

**Comment by diraol** [comment]
@marcoamarelo essa está resolvida?

**Comment by marcoamarelo** [comment]
Sim Diego, eu resolvi junto com outro hotfix dos comentários repetidos nas
notícias.

Marco Antonio Konopacki

## @marcoamarelo

...... __@
...._ \ >_
...(_)/ (_)

2015-04-15 10:34 GMT-03:00 Diego Rabatone Oliveira <notifications@github.com
