### ISSUE TITLE
Programar backend do carrousel

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-sitebase#64]
Relacionada a #51 e #63

**Comment by diraol** [comment]
Relacionado a #144

**Comment by diraol** [comment]
@marilucchesi quais eram as medidas das imagens/vídeos mesmo? (versão com texto e versão full width)

**Comment by marilucchesi** [comment]
@diraol dá uma olhada:
![uploads/a2823eba-a091-4cd6-80f4-5fd2d86d5e8d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa2823eba-a091-4cd6-80f4-5fd2d86d5e8d%2Fblob)

![uploads/dce7fce8-626a-40c3-9e83-5a9282e944d2/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdce7fce8-626a-40c3-9e83-5a9282e944d2%2Fblob)

**Comment by diraol** [comment]
Valeu! =)

**Comment by diraol** [comment]
Adicionar "Link" no backend e aplicá-lo no texto, caso houver, ou no frame, caso não houver.
