### ISSUE TITLE
Melhorar texto e layout do box "como participar""

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#73]

**Comment by diraol** [comment]
@marilucchesi isso foi resolvido? (Estou perguntando pq não achei o pull-request e/ou commit que resolvesse essa issue, mas se já foi beleza, é só fechar a issue....

**Comment by marilucchesi** [comment]
Já, foi documentado. Futuramente implementamos, aí criamos uma issue nova.
