### ISSUE TITLE
Adicionar textos em "proponha um debate"

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#77]
Textos em: https://docs.google.com/document/d/16wgU9MARZ5fTh68JZVeL5VXpDsnnwyJ0VUNnupCq0v0/edit?usp=sharing

**Comment by thsl** [comment]
Vou aproveitar esta issue para reorganizar a área de propor debates (que se desorganizou devido aos meus pull requests que foram feitos de forma indevida, em branchs erradas)
