### ISSUE TITLE
Fazer backend da nova página de cadastro

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#78]
relacionado ao #55

**Comment by marilucchesi** [comment]
arquivo em participacao-tema > wp-singup.php
https://github.com/pensandoodireito/participacao-tema/pull/85

**Comment by marilucchesi** [comment]
Texto pós revisão:

Por que devo me cadastrar?
Porque esta é uma plataforma que insere a sociedade no debate de projetos ou anteprojetos de lei no Brasil. Criar leis não é uma tarefa fácil e não deve estar somente nas mãos dos magistrados.  Nosso objetivo é complementar - e em alguns casos até mesmo substituir - formas tradicionais de elaboração de leis. 
Você pode propor uma nova redação a cada artigo do texto normativo, contestar argumentos de outros participantes e agregar informações como artigos, textos e notícias. Por isso, ao se cadastrar, você será uma parte importante do processo, e sua opinião pode influenciar leis sobre assuntos que interessam ao nosso país.

O que são "debates"?
Na plataforma, os "debates" podem ser projetos ou anteprojetos de lei que estão abertos à participação social para sua consolidação. Eles não têm caráter plebiscitário, mas se destinam a coletar opiniões diversas e qualificadas sobre os temas em discussão. Depois dessa fase de discussão, as contribuições serão sistematizadas com a colaboração de acadêmicos, representantes da sociedade civil, membros do segmento empresarial e demais interessados.

Quem promove essa iniciativa?
Esta plataforma de participação da sociedade no processo legislativo é uma iniciativa da Secretaria de Assuntos Legislativos do Ministério da Justiça.

Quais os termos de uso da plataforma?
Nossos termos de uso são bem razoáveis. Leia os termos de uso.

**Comment by diraol** [comment]
Algumas referências:
- http://designmodo.com/wordpress-custom-registration/
- https://codex.wordpress.org/Customizing_the_Registration_Form
- http://www.onextrapixel.com/2013/01/24/how-to-create-an-effective-registration-page-for-wordpress-sign-up/
