### ISSUE TITLE
Melhoria visual no box de compartilhamento em uma Pauta

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#85]
Contemplada pela tarefa #123

**Comment by marilucchesi** [comment]
Atual:
![uploads/a9024fe2-7d57-4b9f-8dfc-236c751cb10a/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa9024fe2-7d57-4b9f-8dfc-236c751cb10a%2Fblob)

**Comment by marcoamarelo** [comment]
Será implementada pela #53
