### ISSUE TITLE
Ajustar backend da página de notícias

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-sitebase#88]
relacionado ao #87

**Comment by marilucchesi** [comment]
verificar ainda o comportamento do botão "mais notícias" para ser exibido somente quando houver necessidade. (mostrar 10 noticias por vez nesta página?)

**Comment by diraol** [comment]
Problema:
Ao selecionar algumas categorias (p.ex: Assuntos Legislativos) o menu desaparece.
